- name: Install packages for libvirt host
  dnf: name="{{ item }}" state="latest"
  with_items:
  - libvirt-daemon-kvm
  - libvirt-python
  - libvirt-client
  - mkisofs

- name: Ensure libvirtd is running
  service: name=libvirtd state=started

- name: Capture current tuned profile
  shell: tuned-adm active | rev | cut -f 1 -d " " | rev
  register: tuned_return
  changed_when: false

- name: Enable virtual-host tuned profile
  command: tuned-adm profile virtual-host
  when: tuned_return.stdout != "virtual-host"
  changed_when: true
