- name: Install packages for libvirt host
  dnf: name="{{ item }}" state="latest"
  with_items:
  - libvirt-daemon-kvm
  - libvirt-python
  - libvirt-client
  - mkisofs

- name: Ensure libvirtd is running
  service: name=libvirtd state=started

- name: Capture current tuned profile
  shell: tuned-adm active | rev | cut -f 1 -d " " | rev
  register: tuned_return
  changed_when: false

- name: Enable virtual-host tuned profile
  command: tuned-adm profile virtual-host
  when: tuned_return.stdout != "virtual-host"
  changed_when: true

- name: Define libvirt storage pool
  virt_pool:
    command: define
    name: "{{ libvirt_storage_pool.name }}"
    xml: '{{ lookup("template", "pool.xml.j2") }}'

- name: Build libvirt storage pool
  virt_pool:
    command: build
    name: "{{ libvirt_storage_pool.name }}"
    mode: no_overwrite
  failed_when: false

- name: Activate libvirt storage pool
  virt_pool:
    state: active
    name: "{{ libvirt_storage_pool.name }}"

- name: Define libvirt network
  virt_net:
    command: define
    name: "{{ libvirt_network.name }}"
    xml: "{{ lookup('template', 'network.xml.j2') }}"

- name: Activate libvirt network
  virt_net:
    state: active
    name: "{{ libvirt_network.name }}"
